### ISSUE TITLE
Cannot set image for a product

### ISSUE THREAD

**Issue by heojee1** [akeneo/api-php-client#180]
I have an attribute named 'thumbnail' for each product. I have images in a folder 'scraper/images.' When I tried setting thumbnail via the path to the image as follows:
```
    $client->getProductApi()->upsert($product_id, [
        'values' => [
            'thumbnail' => [
                [
                    'data' => '/scraper/images/' . $product_name . '.jpeg',
                    'locale' => null,
                    'scope' => null
                ]
            ]
        ]
    ]);
```

I get the following error message:
```
PHP Fatal error:  Uncaught Akeneo\Pim\ApiClient\Exception\UnprocessableEntityHttpException: Property "thumbnail" expects a valid pathname as data, "/scraper/images/at.jpeg" given. Check the expected format on the API documentation. (see https://api.akeneo.com/php-client/exception.html#unprocessable-entity-exception) in /srv/pim/client/vendor/akeneo/api-php-client/src/Client/HttpExceptionHandler.php:58
Stack trace:
#0 /srv/pim/client/vendor/akeneo/api-php-client/src/Client/HttpClient.php(62): Akeneo\Pim\ApiClient\Client\HttpExceptionHandler->transformResponseToException(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /srv/pim/client/vendor/akeneo/api-php-client/src/Client/AuthenticatedHttpClient.php(63): Akeneo\Pim\ApiClient\Client\HttpClient->sendRequest('PATCH', 'http://httpd:80...', Array, '{"values":{"thu...')
#2 /srv/pim/client/vendor/akeneo/api-php-client/src/Client/ResourceClient.php(142): Akeneo\Pim\ApiClient\Client\AuthenticatedHttpClient->sendRequest('PATCH', 'http://httpd:80...', Array, '{"values":{"thu...')
#3 /srv/pim/client/vendor/akeneo/api-php-client/src/Api/ProductApi.php(97): Akeneo\Pim\ApiClient\Client\ResourceClient->upsertResource('http://httpd:80...', Array, Array)
#4 /srv/pim/client/importProducts.php(306): Akeneo\Pim\ApiClient\Api\ProductApi->upsert('1', Array)
#5 /srv/pim/client/importProducts.php(354): createProduct(Object(PDO), Object(Akeneo\Pim\ApiClient\AkeneoPimClient), Array, 'Apple_Products')
#6 /srv/pim/client/importProducts.php(394): createProducts(Object(PDO), Object(Akeneo\Pim\ApiClient\AkeneoPimClient), 'Apple_Products')
#7 /srv/pim/client/importProducts.php(397): execute()
#8 {main}
  thrown in /srv/pim/client/vendor/akeneo/api-php-client/src/Client/HttpExceptionHandler.php on line 58
```

**Comment by alberttomasiak** [comment]
Hi! 

Could you explain how you managed to solve this? 

Thanks!
